### ISSUE TITLE
New tag 1.2.1-0 and maven release

### ISSUE THREAD

**Issue by msignoriniIon** [pdsoftplan/zap-maven-plugin#6]
Hi,

is it possible to have a tag of the master branch published also on maven repositories?
Is there any other pending feature?

I don't know if it is the right way to ask for a new release, if not please suggest me the correct one.

Thanks,
Marco

**Comment by tfcporciuncula** [comment]
It's fine to ask for a release here as an issue. I don't think we have any pending feature on development, so we should be able release a new version right away.

We'll get back to you soon.

**Comment by fabiusks** [comment]
Hi,

@tfcporciuncula and I have just made the release process. We're waiting for the artifacts to reach maven central to close the issue. Changelog must be updated too.

**Comment by fabiusks** [comment]
Released! Thanks for the contributions @msignoriniIon
